AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  rssdynamo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: python3.8
      CodeUri: lambda/
      Description: 'Retrieve RSS feeds and store them in DynamoDB'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
              Resource: '*'
        - ComprehendFullAccess
        - AmazonSESFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref rssfeed
      MemorySize: 3008
      Timeout: 60
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
      Environment:
        Variables:
          dynamo_region: !Ref 'AWS::Region'
          dynamo_table: !Ref rssfeed
          fromemail: aws@marek.rocks
          toemail: marek.kuczynski@gmail.com
          sendemails: 'n'
      Tracing: Active
      ReservedConcurrentExecutions: 3
  rssfeed:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
      - AttributeName: source
        AttributeType: S
      - AttributeName: timest
        AttributeType: S
      - AttributeName: allts
        AttributeType: S
      KeySchema:
      - AttributeName: source
        KeyType: HASH
      - AttributeName: timest
        KeyType: RANGE  
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl
      GlobalSecondaryIndexes:
      - IndexName: allts
        KeySchema:
        - AttributeName: allts
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
